#!/usr/bin/env python3
"""Populate stub Umamusume character profiles using the Special_Week.md layout.

A stub is any file in the Character folder that is under STUB_MAX_BYTES
(currently just a "# Name" heading). Files that already have content are
never touched, so the script is safe to re-run.

With --refresh, files previously generated by this script are regenerated too.
They are recognised by GENERATED_MARK (a comment on the last line). Delete that
line from a profile you have expanded by hand and the script will leave it alone.

Sources (all GameTora, server-rendered):
  - Character page:  profile facts, real-life counterpart, character ID
  - Version pages:   /characters/<id><nn>-<slug> for nn = 01, 02, ...
                     release date, base stats, growth bonuses, aptitudes,
                     career objectives, art URLs

Only facts that were actually parsed are written. Anything that could not be
confirmed is listed under "Gaps" instead of being guessed.

Game-specific short flavor text (ears, tail, family, trivia, weight line) is
not copied. If GROQ_API_KEY is set it is reworded with a free-tier Groq model;
otherwise those rows are left out and listed as gaps.

Usage:
  python populate_character_stubs.py [--limit N] [--only A,B] [--dry-run] [--refresh]
"""
import argparse
import html
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from html.parser import HTMLParser
from pathlib import Path

CHAR_DIR = Path(os.environ.get("CHARACTER_DIR", "LilyAiGameSpace/Umamusume/Character"))
STUB_MAX_BYTES = 200
REQUEST_DELAY = 2.0
MAX_VERSIONS = 9
GENERATED_MARK = "<!-- generated by populate_character_stubs.py; delete this line to protect hand edits -->"
OLD_MARKER = "Not filled in yet (see Gaps)."  # written by the first version of this script
USER_AGENT = "LilyAi-profile-bot (+https://github.com/UmakraftCircle/DmLilyAi)"
GAMETORA = "https://gametora.com/umamusume/characters/"
GT_IMG = "https://gametora.com/images/umamusume/characters/"
GT_MEDIA = "https://media.gametora.com/umamusume/characters/profile/"
WIKI_RAW = (
    "https://en.wikipedia.org/w/index.php"
    "?title=List_of_Umamusume:_Pretty_Derby_characters&action=raw"
)
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL = os.environ.get("GROQ_MODEL", "openai/gpt-oss-20b")

# File stem -> GameTora slug, only for names where lowercase-with-hyphens is wrong.
# Example: "KS_Miracle": "k-s-miracle"
SLUG_OVERRIDES: dict[str, str] = {}

LABELS = [
    "Japanese name", "Voice actor", "Birthday", "School", "Dorm", "Height",
    "Weight", "Three sizes", "Shoe size", "Strong points", "Weak points",
    "Ears", "Tail", "Family", "Secrets", "Country of birth", "Races", "Wins",
    "Record", "Earnings", "Date of birth", "Date of death", "Profile",
    "Measurements", "Official art", "Character", "Background", "Version",
    "RL Counterpart", "Release date", "Base stats", "Stat bonuses", "Aptitude",
    "Objectives", "Surface", "Distance", "Strategy",
]
LABEL_SET = set(LABELS)

# Numbers, dashes and units that the page splits into separate text nodes
# (for example "86", "-", "56", "-", "88" or "162", "cm").
CONTINUATION = re.compile(r"^(?:[-–—/]|\d+(?:\.\d+)?|cm|kg|m|JPY)$")

STAT_NAMES = ["Speed", "Stamina", "Power", "Guts", "Wit"]
APTITUDES = [
    ("Surface", "Turf", "Turf"), ("Surface", "Dirt", "Dirt"),
    ("Distance", "Short", "Short"), ("Distance", "Mile", "Mile"),
    ("Distance", "Medium", "Medium"), ("Distance", "Long", "Long"),
    ("Strategy", "Front", "Front Runner"), ("Strategy", "Pace", "Pace Chaser"),
    ("Strategy", "Late", "Late Surger"), ("Strategy", "End", "End Closer"),
]


class TextLines(HTMLParser):
    """Flatten HTML into a list of non-empty text lines.

    Aptitude ranks are images on the page, so the alt text of rank icons is
    emitted as a line too.
    """

    SKIP = {"script", "style", "noscript", "svg"}

    def __init__(self):
        super().__init__()
        self.lines: list[str] = []
        self._skip = 0

    def handle_starttag(self, tag, attrs):
        if tag in self.SKIP:
            self._skip += 1
        elif tag == "img" and not self._skip:
            a = dict(attrs)
            if "/ui/rank/" in (a.get("src") or "") and a.get("alt"):
                self.lines.append(a["alt"].strip())

    def handle_endtag(self, tag):
        if tag in self.SKIP and self._skip:
            self._skip -= 1

    def handle_data(self, data):
        if self._skip:
            return
        text = " ".join(data.split())
        if text:
            self.lines.append(text)


def fetch(url: str) -> str | None:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as err:
        if err.code == 404:
            return None
        raise


def to_lines(raw: str) -> list[str]:
    parser = TextLines()
    parser.feed(raw)
    return parser.lines


def field(lines: list[str], label: str) -> str | None:
    for i, line in enumerate(lines):
        if line == label and i + 1 < len(lines):
            first = lines[i + 1]
            if first in LABEL_SET:
                return None
            parts = [first]
            # Numeric values can be split across several text nodes; join them.
            if CONTINUATION.match(first):
                j = i + 2
                while j < len(lines) and lines[j] not in LABEL_SET and CONTINUATION.match(lines[j]):
                    parts.append(lines[j])
                    j += 1
            return " ".join(parts)
    return None


def between(lines: list[str], start: str, end: str | None = None) -> list[str]:
    if start not in lines:
        return []
    i = lines.index(start) + 1
    j = len(lines)
    if end and end in lines[i:]:
        j = lines.index(end, i)
    return lines[i:j]


def secrets(lines: list[str]) -> list[str]:
    out = []
    for line in lines:
        if line.startswith("Did you know?"):
            out.append(line.removeprefix("Did you know?").strip())
    return out[:3]


def tagline(lines: list[str], display: str) -> str | None:
    if "Japanese name" not in lines:
        return None
    prev = lines[lines.index("Japanese name") - 1]
    if prev in (display, "Character versions") or len(prev) < 10:
        return None
    return prev


# ---------------------------------------------------------------- version pages

def parse_stats(lines: list[str]) -> dict[int, list[int]]:
    """{star count: [speed, stamina, power, guts, wit]}"""
    seg = between(lines, "Base stats", "Stat bonuses")
    out: dict[int, list[int]] = {}
    i = 0
    while i < len(seg):
        if re.fullmatch(r"(?:\u2b50\ufe0f?)+", seg[i]):
            stars = seg[i].count("\u2b50")
            nums, j = [], i + 1
            while j < len(seg) and re.fullmatch(r"\d+", seg[j]) and len(nums) < 5:
                nums.append(int(seg[j]))
                j += 1
            if len(nums) == 5:
                out[stars] = nums
            i = j
        else:
            i += 1
    return out


def parse_bonuses(lines: list[str]) -> str | None:
    seg = between(lines, "Stat bonuses", "Aptitude")
    vals = [s for s in seg if re.fullmatch(r"\d+%|-", s)][:5]
    if len(vals) != 5:
        return None
    text = ", ".join(f"{n} {v}" for n, v in zip(STAT_NAMES, vals) if v != "-")
    return text or "None"


def parse_aptitudes(lines: list[str]) -> list[tuple[str, str, str]] | None:
    seg = between(lines, "Aptitude", "Objectives")
    out = []
    for cat, label, shown in APTITUDES:
        rank = None
        for k, s in enumerate(seg):
            if s == label and k + 1 < len(seg) and re.fullmatch(r"[SABCDEFG]", seg[k + 1]):
                rank = seg[k + 1]
                break
        if rank is None:
            return None
        out.append((cat, shown, rank))
    return out


def parse_objectives(lines: list[str]) -> list[tuple[str, str, str, str, str]]:
    seg = between(lines, "Objectives", "Character Rate Up")
    rows = []
    i = 0
    while i < len(seg):
        m = re.match(r"^(\d+)\.\s+(.+)$", seg[i])
        if m and i + 3 < len(seg):
            turn = re.match(r"^Turn (\d+)", seg[i + 1])
            if turn:
                race = seg[i + 3].replace(" \u2013 ", ", ")
                rows.append((m.group(1), m.group(2), turn.group(1), seg[i + 2], race))
                i += 4
                continue
        i += 1
    return rows


def parse_version(raw: str, num: int, vid: str, url: str, display: str) -> dict | None:
    lines = to_lines(raw)
    if "Base stats" not in lines:
        return None
    title_m = re.search(r"<title>([^<]+)</title>", raw)
    title = html.unescape(title_m.group(1).split("|")[0].strip()) if title_m else display
    label_m = re.search(r"\(([^)]+)\)\s*$", title)
    epithet = None
    for k, s in enumerate(lines):
        if "Character versions" in s and k + 1 < len(lines):
            cand = lines[k + 1].strip("[] ")
            if cand and cand != display and not re.match(r"^[\d\u2b50]", cand):
                epithet = cand
            break
    stars_line = next((s for s in lines if re.fullmatch(r"(?:\u2b50\ufe0f?)+", s)), None)
    release = field(lines, "Release date")
    return {
        "num": num,
        "vid": vid,
        "url": url,
        "title": title,
        "label": label_m.group(1) if label_m else "Original",
        "epithet": epithet,
        "rarity": stars_line.count("\u2b50") if stars_line else None,
        "release": release if release and re.fullmatch(r"\d{4}-\d{2}-\d{2}", release) else None,
        "stats": parse_stats(lines),
        "bonuses": parse_bonuses(lines),
        "apts": parse_aptitudes(lines),
        "objectives": parse_objectives(lines),
    }


def fetch_versions(cid: str, slug: str, display: str, log) -> list[dict]:
    versions = []
    for n in range(1, MAX_VERSIONS + 1):
        vid = f"{cid}{n:02d}"
        url = f"{GAMETORA}{vid}-{slug}"
        try:
            raw = fetch(url)
        finally:
            time.sleep(REQUEST_DELAY)
        if raw is None:
            break
        ver = parse_version(raw, n, vid, url, display)
        if ver is None:
            log(f"  version {vid}: page layout not recognised, stopping")
            break
        versions.append(ver)
    return versions


# ---------------------------------------------------------------- optional bits

def reword(texts: list[str]) -> list[str] | None:
    """Paraphrase short flavor lines with Groq. Returns None if unavailable."""
    key = os.environ.get("GROQ_API_KEY")
    if not key or not texts:
        return None
    prompt = (
        "Reword each line below in your own words as a neutral, encyclopedia-style "
        "fact. Do not add any information that is not in the line. Keep each under "
        "25 words. Return ONLY a JSON array of strings, same length and order.\n\n"
        + json.dumps(texts, ensure_ascii=False)
    )
    body = json.dumps({
        "model": GROQ_MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.2,
    }).encode()
    req = urllib.request.Request(GROQ_URL, data=body, headers={
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
        "User-Agent": USER_AGENT,
    })
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            content = json.load(resp)["choices"][0]["message"]["content"]
        arr = json.loads(content[content.index("["): content.rindex("]") + 1])
        if len(arr) == len(texts) and all(isinstance(x, str) and x.strip() for x in arr):
            return [x.strip() for x in arr]
    except Exception as exc:  # optional step, never fatal
        print(f"  reword skipped: {exc}")
    return None


_wiki_cache: dict[str, str | None] = {}


def wiki_voice_actor(display: str) -> str | None:
    """Best-effort voice actor lookup in the Wikipedia character list."""
    if "text" not in _wiki_cache:
        try:
            _wiki_cache["text"] = fetch(WIKI_RAW)
        except Exception:
            _wiki_cache["text"] = None
    text = _wiki_cache["text"]
    if not text:
        return None
    pos = text.find(display)
    if pos < 0:
        return None
    chunk = text[pos: pos + 300]
    m = re.search(r"[Vv]oiced by\W+(?:\{\{[^|}]*\|)?([A-Z][A-Za-z.'-]+(?: [A-Z][A-Za-z.'-]+){1,3})", chunk)
    return m.group(1) if m else None


# ---------------------------------------------------------------- rendering

def cell(value: str | None) -> str:
    return value if value else "Not confirmed"


def format_earnings(raw: str | None) -> str | None:
    if not raw:
        return None
    digits = raw.replace("JPY", "").replace(",", "").strip()
    if digits.isdigit():
        return f"{int(digits):,} JPY"
    return raw if "JPY" in raw else f"{raw} JPY"


def version_heading(name: str, v: dict) -> str:
    text = f"{name}"
    if v["label"] != "Original":
        text += f" ({v['label']})"
    if v["epithet"]:
        text += f" [{v['epithet']}]"
    else:
        text += " (Original)" if v["label"] == "Original" else ""
    return text


def apt_table(apts: list[tuple[str, str, str]]) -> list[str]:
    out = ["| Category | Type | Rank |", "|----------|------|------|"]
    out += [f"| {c} | {t} | {r} |" for c, t, r in apts]
    top = [t for _, t, r in apts if r in ("S", "A")]
    if top:
        out += ["", f"Rank A or higher: {', '.join(top)}."]
    return out


def objective_table(rows: list[tuple[str, str, str, str, str]]) -> list[str]:
    out = ["| # | Objective | Turn | Timing | Race |", "|---|-----------|------|--------|------|"]
    out += [f"| {n} | {t} | {turn} | {timing} | {race} |" for n, t, turn, timing, race in rows]
    return out


def render_game_data(name: str, versions: list[dict]) -> list[str]:
    n = len(versions)
    apt_sets = {json.dumps(v["apts"]) for v in versions}
    obj_sets = {json.dumps(v["objectives"]) for v in versions}
    shared_apts = len(apt_sets) == 1 and versions[0]["apts"] is not None
    shared_objs = len(obj_sets) == 1 and bool(versions[0]["objectives"])

    out = ["---", "", "## Game data: versions", ""]
    same = []
    if shared_apts:
        same.append("aptitudes")
    if shared_objs:
        same.append("career objectives")
    intro = f"{name} has {n} playable version{'s' if n != 1 else ''} in the game."
    if n > 1 and same:
        intro += f" {' and '.join(same).capitalize()} are identical across all versions."
    out += [intro, "", "| Version | GameTora page |", "|---------|---------------|"]
    out += [f"| {version_heading(name, v)} | {v['url']} |" for v in versions]

    if shared_apts:
        out += ["", "### Shared aptitudes" + (" (all versions)" if n > 1 else ""), ""]
        out += apt_table(versions[0]["apts"])
    if shared_objs:
        out += ["", "### Shared career objectives" + (" (all versions)" if n > 1 else ""), ""]
        out += objective_table(versions[0]["objectives"])

    for i, v in enumerate(versions, 1):
        out += ["", f"### Version {i}: {version_heading(name, v)}", "",
                "| Field | Details |", "|-------|---------|",
                f"| Release date | {cell(v['release'])} |",
                f"| Rarity | {str(v['rarity']) + ' star (base)' if v['rarity'] else 'Not confirmed'} |",
                f"| Stat growth bonuses | {cell(v['bonuses'])} |"]
        if v["stats"]:
            out += ["", "| Stats | Speed | Stamina | Power | Guts | Wit |",
                    "|-------|-------|---------|-------|------|-----|"]
            for stars in sorted(v["stats"]):
                out.append(f"| {stars} star | " + " | ".join(str(x) for x in v["stats"][stars]) + " |")
        if not shared_apts and v["apts"]:
            out += ["", "**Aptitudes**", ""] + apt_table(v["apts"])
        if not shared_objs and v["objectives"]:
            out += ["", "**Career objectives**", ""] + objective_table(v["objectives"])

    with_5 = [v for v in versions if 5 in v["stats"]]
    if n > 1 and with_5:
        out += ["", "### Version comparison", "",
                "| Version | Release | Speed (5 star) | Stamina (5 star) | Power (5 star) | Guts (5 star) | Wit (5 star) | Growth bonuses |",
                "|---------|---------|----------------|------------------|----------------|---------------|--------------|----------------|"]
        for v in with_5:
            s = v["stats"][5]
            out.append(f"| {version_heading(name, v)} | {cell(v['release'])} | " + " | ".join(str(x) for x in s)
                       + f" | {cell(v['bonuses'])} |")
    return out


def render(name: str, url: str, lines: list[str], reworded: dict[str, str], voice: str | None,
           voice_from_wiki: bool, cid: str | None, versions: list[dict]) -> tuple[str, list[str]]:
    jp = field(lines, "Japanese name")
    gaps = [
        "Overview, background and personality: not filled in yet.",
        "Appearances (anime, game, other media): not filled in yet.",
        "Unique skills, build notes, obtain methods and support cards: not filled in yet.",
    ]
    if not reworded:
        gaps.insert(0, "Ears, tail, family, trivia and weight rows were left out (game text is not copied).")
    if not versions:
        gaps.append("Game data (versions, stats, aptitudes, objectives): the GameTora version pages could not be read.")
    else:
        for v in versions:
            missing = [w for w, ok in (("stats", v["stats"]), ("growth bonuses", v["bonuses"]),
                                       ("aptitudes", v["apts"]), ("objectives", v["objectives"]),
                                       ("release date", v["release"])) if not ok]
            if missing:
                gaps.append(f"{version_heading(name, v)}: could not parse {', '.join(missing)}.")

    height = field(lines, "Height")
    height_cell = height if height and re.search(r"\d", height) else None
    infobox = [
        ("Name", name),
        ("Japanese name", cell(jp)),
        ("Voice actor", cell(voice)),
        ("Birthday", cell(field(lines, "Birthday"))),
        ("Height", cell(height_cell)),
        ("Three sizes", cell(field(lines, "Three sizes"))),
        ("Shoe size", cell(field(lines, "Shoe size"))),
        ("School", cell(field(lines, "School"))),
        ("Dorm", cell(field(lines, "Dorm"))),
        ("Strong point", cell(field(lines, "Strong points"))),
        ("Weak point", cell(field(lines, "Weak points"))),
    ]
    if reworded.get("weight"):
        infobox.insert(5, ("Weight", reworded["weight"]))
    if versions:
        labels = ", ".join(v["epithet"] or v["label"] for v in versions)
        infobox.append(("Game versions", f"{len(versions)} ({labels})"))

    out = [f"# {name}", ""]
    if jp:
        out.append(f"**Japanese name:** {jp}")
    out.append("**Series:** Umamusume: Pretty Derby (anime, game and franchise)")
    if reworded.get("tagline"):
        out.append(f"**Tagline (game):** {reworded['tagline']}")
    out += [
        "",
        "> Profile page in the style of an encyclopedia entry. Facts are gathered from the sources "
        "listed at the bottom and reworded. Values come from the sources' data at the time of the "
        "last automated update and can change with game updates.",
        "",
        "---",
        "",
        "## Infobox",
        "",
        "| Field | Details |",
        "|-------|---------|",
    ]
    out += [f"| {k} | {v} |" for k, v in infobox]

    out += ["", "## Overview", "", "Not filled in yet.", "", "## Background", "", "Not filled in yet."]

    detail_rows = [
        ("Ears", reworded.get("ears")), ("Tail", reworded.get("tail")),
        ("Family", reworded.get("family")),
    ]
    for i in range(3):
        detail_rows.append((f"Trivia {i + 1}", reworded.get(f"secret{i}")))
    detail_rows = [(k, v) for k, v in detail_rows if v]
    if detail_rows:
        out += ["", "## Profile details (game)", "", "| Detail | Description |", "|--------|-------------|"]
        out += [f"| {k} | {v} |" for k, v in detail_rows]

    rl = [
        ("Country of birth", field(lines, "Country of birth")),
        ("Date of birth", field(lines, "Date of birth")),
        ("Date of death", field(lines, "Date of death")),
        ("Races", field(lines, "Races")),
        ("Wins", field(lines, "Wins")),
        ("Record (1st-2nd-3rd-other)", field(lines, "Record")),
        ("Earnings", format_earnings(field(lines, "Earnings"))),
    ]
    rl = [(k, v) for k, v in rl if v]
    out += ["", "## Real-life counterpart", ""]
    if rl:
        out += [
            f"{name} is named after and based on a Japanese racehorse.", "",
            "| Field | Details |", "|-------|---------|",
        ]
        out += [f"| {k} | {v} |" for k, v in rl]
    else:
        out.append("Not confirmed from any source.")
        gaps.append("Real-life counterpart details were not found on the source page.")

    out += ["", "## Appearances", "", "Not filled in yet.", ""]
    if versions:
        out += render_game_data(name, versions)
    else:
        out += ["---", "", "## Game data: versions", "", "Not filled in yet (see Gaps)."]

    out += ["", "---", "", "## Gaps", ""]
    out += [f"- {g}" for g in gaps]

    out += ["", "## Sources", "", "| Source | URL |", "|--------|-----|",
            f"| GameTora profile | {url} |"]
    for v in versions:
        out.append(f"| GameTora, {version_heading(name, v)} | {v['url']} |")
    if voice_from_wiki:
        out.append("| Wikipedia, list of characters (voice actor) | "
                   "https://en.wikipedia.org/wiki/List_of_Umamusume:_Pretty_Derby_characters |")
    out += ["", "Game materials are copyright Cygames, Inc."]

    if cid:
        out += ["", "## Images", "",
                "Images are kept as their original URLs.", "",
                "| Description | URL |", "|-------------|-----|"]
        for v in versions:
            out.append(f"| {version_heading(name, v)} standing art (GameTora) | {GT_IMG}chara_stand_{cid}_{v['vid']}.png |")
        out.append(f"| Profile art | {GT_MEDIA}{cid}.png |")
        out.append(f"| Character icon | {GT_IMG}icons/chr_icon_{cid}.png |")

    out += ["", GENERATED_MARK, ""]
    return "\n".join(out), gaps


# ---------------------------------------------------------------- main

def is_stub(path: Path) -> bool:
    return path.stat().st_size < STUB_MAX_BYTES


def is_generated(path: Path) -> bool:
    """True for files this script wrote earlier and nobody has claimed since."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return False
    return GENERATED_MARK in text or OLD_MARKER in text


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=10)
    ap.add_argument("--only", default="", help="comma-separated file stems, e.g. Kitasan_Black,Rice_Shower")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--refresh", action="store_true",
                    help="also regenerate files this script created earlier")
    args = ap.parse_args()

    only = {s.strip() for s in args.only.split(",") if s.strip()}
    stubs = sorted(
        p for p in CHAR_DIR.glob("*.md")
        if (is_stub(p) or (args.refresh and is_generated(p))) and (not only or p.stem in only)
    )
    print(f"{len(stubs)} file(s) to process; processing up to {args.limit}")

    done, skipped = [], []
    for path in stubs:
        if len(done) >= args.limit:
            break
        stem = path.stem
        display = stem.replace("_", " ")
        slug = SLUG_OVERRIDES.get(stem, stem.lower().replace("_", "-"))
        url = GAMETORA + slug
        print(f"- {stem}: {url}")
        try:
            raw = fetch(url)
        except Exception as exc:
            skipped.append((stem, f"fetch error: {exc}"))
            continue
        finally:
            time.sleep(REQUEST_DELAY)
        if raw is None:
            skipped.append((stem, "404 (add to SLUG_OVERRIDES)"))
            continue

        lines = to_lines(raw)
        # Sanity check: must have parsed the basics or we write nothing.
        if not field(lines, "Japanese name") or not (field(lines, "Birthday") or field(lines, "Height")):
            skipped.append((stem, "page layout not recognised"))
            continue

        cid_m = re.search(r"characters/profile/(\d+)\.png", raw)
        cid = cid_m.group(1) if cid_m else None
        versions: list[dict] = []
        if cid:
            try:
                versions = fetch_versions(cid, slug, display, print)
            except Exception as exc:
                print(f"  version fetch failed: {exc}")
        else:
            print("  character ID not found on page; skipping version data")
        print(f"  {len(versions)} version(s) parsed")

        voice = field(lines, "Voice actor")
        from_wiki = False
        if not voice:
            voice = wiki_voice_actor(display)
            from_wiki = bool(voice)

        flavor = {
            "tagline": tagline(lines, display),
            "weight": field(lines, "Weight"),
            "ears": field(lines, "Ears"),
            "tail": field(lines, "Tail"),
            "family": field(lines, "Family"),
        }
        for i, s in enumerate(secrets(lines)):
            flavor[f"secret{i}"] = s
        flavor = {k: v for k, v in flavor.items() if v}
        keys = list(flavor)
        new = reword([flavor[k] for k in keys])
        reworded = dict(zip(keys, new)) if new else {}

        content, gaps = render(display, url, lines, reworded, voice, from_wiki, cid, versions)
        if args.dry_run:
            print(f"  [dry-run] would write {len(content)} bytes, {len(gaps)} gap(s)")
        else:
            path.write_text(content, encoding="utf-8")
            print(f"  wrote {len(content)} bytes")
        done.append(f"{stem} ({len(versions)} version(s), {len(gaps)} gap(s))")

    summary = [f"Populated: {len(done)}"] + [f"- {s}" for s in done]
    summary += [f"Skipped: {len(skipped)}"] + [f"- {s}: {why}" for s, why in skipped]
    text = "\n".join(summary)
    print("\n" + text)
    step_summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if step_summary:
        with open(step_summary, "a", encoding="utf-8") as fh:
            fh.write("## Character stub run\n\n" + text + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
